import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ChartColumnBigIcon } from "lucide-react";
import Link from "next/link";
import { ClerkProvider, SignInButton, SignUpButton, SignedOut, SignedIn } from "@clerk/nextjs";
import { Button } from "@/components/ui/button";


const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <nav className="bg-primary p-4 text-white h-20 flex items-center justify-between">
          <Link href="/" className="font-bold text-2xl flex gap-1 items-center" >
            <ChartColumnBigIcon className="text-lime-500"/>NextCash
          </Link>
        <div>
          <SignedOut>
            <div className="flex items-center">
{/* as child does render anything in the Button element, it passes everything like props and styling of the shadcn ui button to the nested element in */}
              <Button asChild variant="link" className="text-white">
                <SignInButton/>
              </Button>
                <Button asChild variant="link" className="text-white">
                <SignUpButton/>
              </Button>
              
            </div>
          </SignedOut>
          <SignedIn>
            Signed In
          </SignedIn>
        </div>
        </nav>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}


// ClerkProvider is used for binding the whole application under the Clerk authentication, its a library that allows users different methodods authentication